runtime: nodejs
manual_scaling:
  instances: 2
env: flex
beta_settings:
  cloud_sql_instances: buy-and-seller:asia-south2:buy-and-sell-db
env_variables:
  DB_USER: hapi-server
  DB_PASS: abc123!
  DB_NAME: buy-and-sell
  DB_SOCKET: /cloudsql/buy-and-seller:asia-south2:buy-and-sell-db
  